import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const html = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MatchBot × POV Store · Preview</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#070b18;color:#e8edf7;font:15px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;min-height:100vh}.shell{max-width:1160px;margin:auto;padding:42px 22px}.top{display:flex;justify-content:space-between;align-items:end;gap:24px;margin-bottom:26px}.badge{display:inline-flex;gap:7px;align-items:center;color:#74e7b2;background:#12382d;border:1px solid #276a51;border-radius:99px;padding:6px 11px;font-size:12px;font-weight:700}.dot{width:7px;height:7px;background:#4ade80;border-radius:50%;box-shadow:0 0 12px #4ade80}h1{font-size:36px;line-height:1.1;margin:14px 0 8px;letter-spacing:-.03em}p{margin:0;color:#8995aa}.tool{color:#64748b}.tool code{color:#67e8f9}.grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:22px}.card{background:#0d1324;border:1px solid #202a3e;border-radius:24px;padding:21px;box-shadow:0 24px 70px #0005}.head{display:flex;justify-content:space-between;align-items:center;padding-bottom:17px;border-bottom:1px solid #202a3e}.head strong{display:block}.head small{display:block;color:#64748b;margin-top:2px}.chat{min-height:330px;padding:22px 0;display:flex;flex-direction:column;gap:13px}.bubble{max-width:88%;padding:12px 15px;border-radius:17px}.user{margin-left:auto;background:#059669;border-bottom-right-radius:4px}.bot{background:#1a2336;border-bottom-left-radius:4px}.muted{color:#94a3b8}.composer{display:flex;gap:9px;padding-top:17px;border-top:1px solid #202a3e}input{width:100%;background:#080d1b;color:#fff;border:1px solid #273249;border-radius:13px;padding:13px 15px;font:inherit;outline:none}input:focus{border-color:#34d399;box-shadow:0 0 0 3px #34d39922}button{border:0;background:#10b981;color:#04130e;border-radius:13px;padding:0 18px;font-weight:800;cursor:pointer}button:disabled{opacity:.55}.empty{border:1px dashed #273249;border-radius:16px;padding:42px 20px;text-align:center;color:#64748b;margin-top:20px}.products{display:grid;gap:12px;margin-top:20px}.product{background:#080d1b;border:1px solid #202a3e;border-radius:17px;padding:16px}.row{display:flex;justify-content:space-between;gap:15px}.name{font-weight:800;font-size:16px}.model{font-size:12px;color:#64748b;margin-top:3px}.stock{white-space:nowrap;height:max-content;border-radius:99px;padding:5px 9px;font-size:12px;font-weight:800;background:#12382d;color:#74e7b2}.stock.zero{background:#3f1d27;color:#fda4af}.prices{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.price{background:#10182a;border-radius:11px;padding:10px}.price small{display:block;color:#64748b}.price strong{display:block;margin-top:3px}a{display:inline-block;color:#67e8f9;margin-top:13px;text-decoration:none}.error{color:#fda4af;background:#3f1d2744;border:1px solid #7f1d1d;padding:12px;border-radius:13px}@media(max-width:820px){.top{display:block}.tool{margin-top:18px}.grid{grid-template-columns:1fr}h1{font-size:30px}.prices{grid-template-columns:1fr}}
</style></head><body><main class="shell"><div class="top"><div><span class="badge"><span class="dot"></span>VISTA LOCAL · SOLO LECTURA</span><h1>MatchBot × POV Store</h1><p>Mensaje → consulta al catálogo real → datos permitidos → respuesta propuesta.</p></div><div class="tool">Herramienta: <code>catalog.search</code></div></div><div class="grid">
<section class="card"><div class="head"><div><strong>Simulador de conversación</strong><small>Mensaje entrante de WhatsApp</small></div><span>🤖</span></div><div id="chat" class="chat"><div class="muted">Escribí una consulta para comenzar.</div></div><form id="form" class="composer"><input id="query" value="¿Tienen stock de la C200 y cuánto cuesta?" maxlength="500"><button id="send">Enviar</button></form></section>
<section class="card"><div class="head"><div><strong>Datos entregados a MatchBot</strong><small>DTO permitido, sin acceso directo a la base</small></div><span>📦</span></div><div id="results" class="empty">Acá aparecen los productos reales que recibe el agente.</div></section>
</div></main><script>
const form=document.querySelector('#form'),query=document.querySelector('#query'),chat=document.querySelector('#chat'),results=document.querySelector('#results'),send=document.querySelector('#send');
const money=v=>v==null?'—':new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(v);
form.addEventListener('submit',async e=>{e.preventDefault();const text=query.value.trim();if(!text)return;send.disabled=true;chat.innerHTML='<div class="bubble user"></div><div class="bubble bot muted">Consultando catálogo vivo…</div>';chat.firstChild.textContent=text;results.className='empty';results.textContent='Consultando la fuente real…';try{const res=await fetch('/api/integrations/matchbot/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:text})});const body=await res.json();if(!res.ok||body.ok!==true)throw new Error(body.error);const ps=body.products||[];chat.lastChild.className='bubble bot';chat.lastChild.textContent=ps.length?'Encontré '+(ps.length===1?'este producto':'estos productos')+'. '+ps[0].name+' tiene '+ps[0].stock_count+' unidad'+(ps[0].stock_count===1?'':'es')+' disponible'+(ps[0].stock_count===1?'':'s')+' y cuesta '+money(ps[0].price)+'.':'No encontré una coincidencia clara. Pediría el nombre o modelo exacto antes de afirmar precio o stock.';if(!ps.length){results.className='empty';results.textContent='Resultado vacío y seguro: el bot debe pedir una aclaración.'}else{results.className='products';results.innerHTML=ps.map(p=>'<article class="product"><div class="row"><div><div class="name"></div><div class="model"></div></div><span class="stock '+(p.stock_count?'':'zero')+'"></span></div><div class="prices"><div class="price"><small>General</small><strong>'+money(p.price)+'</strong></div><div class="price"><small>Contado</small><strong>'+money(p.cash_price)+'</strong></div><div class="price"><small>Tarjeta</small><strong>'+money(p.card_price)+'</strong></div></div><a target="_blank" rel="noreferrer">Abrir producto ↗</a></article>').join('');[...results.children].forEach((el,i)=>{el.querySelector('.name').textContent=ps[i].name;el.querySelector('.model').textContent=(ps[i].model||'Sin modelo')+' · ID '+ps[i].id.slice(0,8);el.querySelector('.stock').textContent=ps[i].stock_count+' en stock';el.querySelector('a').href=ps[i].url})}}catch(_){chat.lastChild.className='error';chat.lastChild.textContent='No se pudo consultar el catálogo. Revisá la configuración local de Supabase.';results.className='empty';results.textContent='La consulta falló sin exponer datos ni credenciales.'}finally{send.disabled=false}});
</script></body></html>`;

export async function GET() {
  if (process.env.MATCHBOT_PREVIEW_ENABLED !== 'true') {
    return NextResponse.json({ ok: false, error: 'not_found' }, { status: 404 });
  }
  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'",
    },
  });
}
